// // Headerコンポーネントをインポート。これは全てのページに共通で表示されるヘッダーです。
// import Header from '@/components/layout/Header';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// グローバルなスタイルシートをインポート。アプリケーション全体に適用されます。
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// アプリケーションのメタデータ（タイトル、説明など）を定義。SEOに利用されます。
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Header />
        {children} */}
      </body>
    </html>
  );
}
