// // Headerコンポーネントをインポート。これは全てのページに共通で表示されるヘッダーです。
// import Header from '@/components/layout/Header';

import type { Metadata } from "next";
// グローバルなスタイルシートをインポート。アプリケーション全体に適用されます。
import "./globals.css";

// アプリケーションのメタデータ（タイトル、説明など）を定義。SEOに利用されます。
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <Header /> */}
        {/* ページコンポーネントの内容を表示するために {children} は必須です */}
        {children}
      </body>
    </html>
  );
}